### PR TITLE
Dev/oo sunu #13 adding paid008

### PR DESCRIPTION
**Pull request by mcmpp**
This is just the first approach for the export functions. The file is still not well consolidated. I am creating a test for this export functions that will hopefully help for the consolidation of the latest version. The whole flow is coming in the next story but I need this one committed first  (not very well split, my bad)

### CODE REVIEW

**Comment by AlwinEgger** [comment]
But shouldn't it compile to be merged to the sunu branch?

**Comment by rawyler** [comment]
Or maybe create a pain.008 branch that encapsulates both stories. Then that branch could be merged into sunu once the stories are finished.

**Comment by mcmpp** [comment]
Sorry guys, I've just forgotten to include the schema file... actually the story stands by its own but the correctness of the xml created can only be tested manually. That is why the split was not the best.

**Review by AlwinEgger — APPROVED** [review]
Ok for the merge. Don't forget the planned test :)

**Pull request merged**
